apiVersion: v1
kind: ConfigMap
metadata:
  name: zulip-config
  namespace: nekazari
  labels:
    app: zulip
data:
  external-host: "{{ZULIP_DOMAIN}}"
  admin-email: "admin@{{YOUR_DOMAIN}}"
  keycloak-public-url: "https://{{KEYCLOAK_DOMAIN}}/auth"
  keycloak-realm: "nekazari"
